---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/mathew-fleisch/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/src/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.

  - aom
  - asdf
  - autoconf
  - bash-completion
  - bdw-gc
  - c-ares
  - cairo
  - cowsay
  - dav1d
  - doxygen
  - ffmpeg
  - flac
  - fontconfig
  - freetype
  - frei0r
  - fribidi
  - gdbm
  - gettext
  - giflib
  - glib
  - gmp
  - gnutls
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - gobject-introspection
  - graphite2
  - guile
  - harfbuzz
  - helm
  - htop
  - httpie
  - icu4c
  - iperf
  - jemalloc
  - jpeg
  - jq
  - json-c
  - k9s
  - kubectx
  - kubernetes-cli
  - lame
  - leptonica
  - libao
  - libass
  - libbluray
  - libev
  - libevent
  - libffi
  - libgcrypt
  - libgpg-error
  - libidn2
  - libogg
  - libpng
  - libsamplerate
  - libsndfile
  - libsodium
  - libsoxr
  - libtasn1
  - libtiff
  - libtool
  - libunistring
  - libvidstab
  - libvorbis
  - libvpx
  - libyaml
  - little-cms2
  - lzo
  - minikube
  - mcrypt
  - ncurses
  - nettle
  - nghttp2
  - nmap
  - node
  - nvm
  - opencore-amr
  - openjpeg
  - openssl@1.1
  - opus
  - p11-kit
  - pcre
  - pianobar
  - pixman
  - pkg-config
  - pv
  - python@3.9
  - php
  - rav1e
  - readline
  - rtmpdump
  - rubberband
  - sdl2
  - shellcheck
  - ssh-copy-id
  - snappy
  - speex
  - sqlite
  - srt
  - tcl-tk
  - tesseract
  - theora
  - unbound
  - watch
  - webp
  - wget
  - wrk
  - x264
  - x265
  - xvid
  - xz
  - zeromq
  - zimg
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - firefox
  - iterm2
  - licecap
  - sequel-pro
  - sublime-text
  - vagrant

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
